version: '3.8'

services:
  api:
    container_name: fib_api
    build:
      dockerfile: ./src/Dockerfile
      context: .
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src
        target: /app
    command: flask run --host=0.0.0.0
    environment:
      - DEBUG=1