name: Pytest

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v2 

      # # データベース起動
      # - name: Start mongoDB
      #   run: docker-compose -f ./docker/githubactions/docker-compose.yml up -d --build

      # Pythonセットアップ
      - name: Set up Python 3.6.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.8"
          
      # ライブラリインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # # mongoDBにコレクションインポート
      # - name: Import collections
      #   run: docker container exec mongodb /initdata/import_collections.sh

      # ユニットテスト実行
      - name: Run tests
        env:
          PROJECT_HOME: /home/runner/work/repository_name/repository_name
          PYTHONPATH: /home/runner/work/repository_name/repository_name/app
        run: |
          pytest test --cov=app --cov-report=term-missing --junitxml=pytest.xml | tee pytest-coverage.txt
        continue-on-error: true
  
      # テスト結果をプルリクにコメントする
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml